# Generated by Django 4.2.14 on 2025-12-01 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='编程语言')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (等待判题)'), ('JUDGING', 'Judging (正在判题)'), ('AC', 'Accepted (通过)'), ('WA', 'Wrong Answer (错误答案)'), ('TLE', 'Time Limit Exceeded (超时)'), ('MLE', 'Memory Limit Exceeded (超内存)'), ('RE', 'Runtime Error (运行时错误)'), ('CE', 'Compile Error (编译错误)')], default='PENDING', max_length=10, verbose_name='判题状态')),
                ('time_cost_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时 (ms)')),
                ('memory_cost_kb', models.IntegerField(blank=True, null=True, verbose_name='内存 (KB)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='详细反馈')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='提交题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
