# Generated by Django 4.2.14 on 2025-12-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('solved_count', models.IntegerField(default=0, verbose_name='已解决题目数')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('role', models.CharField(choices=[('NORMAL', '普通用户'), ('ADMIN', '管理员'), ('SETTER', '出题人')], default='NORMAL', max_length=10, verbose_name='用户角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
