# Generated by Django 4.2.14 on 2025-12-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('time_limit_ms', models.IntegerField(default=1000, verbose_name='时间限制 (ms)')),
                ('memory_limit_mb', models.IntegerField(default=256, verbose_name='内存限制 (MB)')),
                ('judge_type', models.CharField(choices=[('NORMAL', '标准判题 (Strict Text Compare)'), ('SPJ', '自定义判题 (Special Judge)')], default='NORMAL', max_length=10, verbose_name='判题类型')),
                ('difficulty', models.CharField(choices=[('EASY', '简单'), ('MEDIUM', '中等'), ('HARD', '困难')], default='MEDIUM', max_length=10, verbose_name='难度')),
                ('spj_checker_code', models.FileField(blank=True, null=True, upload_to='checkers/', verbose_name='SPJ 判题程序代码')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='输入数据')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('is_sample', models.BooleanField(default=False, verbose_name='是否为示例用例')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problem.problem', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_zip', models.FileField(upload_to='test_cases/zips/', verbose_name='测试用例ZIP包')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_bundle', to='problem.problem', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目原始文件包',
                'verbose_name_plural': '题目原始文件包',
            },
        ),
    ]
